import{S as f,N as p,K as v,A as l,a as w,i as h}from"./assets/vendor-b6aed901.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))s(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function n(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(o){if(o.ep)return;o.ep=!0;const r=n(o);fetch(o.href,r)}})();const E=document.querySelector(".about-swiper"),g=document.querySelector(".about-swiper-button-next");new f(E,{loop:!0,modules:[p,v],slidesPerView:2,navigation:{nextEl:g},keyboard:{enabled:!0,onlyInViewport:!1},direction:"horizontal",centeredSlides:!0,watchOverflow:!1,breakpoints:{768:{slidesPerView:3},1440:{slidesPerView:6}},disabledClass:"swiper-button-nest-disabled"});new l(".about-education",{duration:600,collapse:!0,openOnInit:[0],showMultiple:!0,onOpen:()=>{aboutArr.classList.add("rotate")},onClose:()=>{aboutArr.classList.remove("rotate")}});document.addEventListener("DOMContentLoaded",function(){document.querySelectorAll(".about-education-list").forEach(t=>{t.addEventListener("click",function(){const n=this.querySelector(".about-arrow"),s=this.querySelector(".text-acordion");n.classList.toggle("rotate"),s.classList.toggle("visually-hidden")})}),new l(".faq-section",{duration:400,showFirstItem:!1})});async function L(){const n="https://portfolio-js.b.goit.study/api/reviews";return(await w.get(n)).data}async function b(e){const s="https://portfolio-js.b.goit.study/api/requests";return(await w.post(s,e)).data}const q=document.querySelector(".content"),u=document.querySelectorAll(".marquee__line");function S(e){return e.getBoundingClientRect().y<0}window.addEventListener("scroll",e=>{S(q)?u.forEach(t=>t.classList.add("animate-block")):u.forEach(t=>t.classList.remove("animate-block"))});document.addEventListener("DOMContentLoaded",function(){document.querySelectorAll(".faq-accordion").forEach(t=>{t.addEventListener("click",function(){const n=this.querySelector(".faq-arrow"),s=this.nextElementSibling;n.classList.toggle("rotate"),s.classList.toggle("visually-hidden")})}),new l(".faq-section",{duration:400,showFirstItem:!1})});const y=document.querySelector(".reviews-main-list"),I=document.querySelector(".reviews-swiper");function A({avatar_url:e,author:t,review:n}){return`<li class="reviews-item swiper-slide">
            
              <img class="reviews-avatar" src="${e}" alt="" width="48" height="48" />
              <h3 class="reviews-item-title">${t}</h3>
              <p class="reviews-item-text">
                ${n}
              </p>
           
          </li>`}function B(e){return e.map(A).join("")}function O(){const e=document.createElement("li"),t=document.createElement("span");e.classList.add("reviews-item-error"),t.textContent="Not found",t.classList.add("reviews-text-error"),e.appendChild(t),y.appendChild(e)}document.addEventListener("DOMContentLoaded",x);async function x(){try{const e=await L(),t=B(e);y.insertAdjacentHTML("beforeend",t)}catch(e){console.error("Error occurred while fetching reviews:",e),O(),h.info({close:!1,position:"topRight",message:"Sorry, an error occurred while fetching reviews. Please try later!"})}}new f(I,{modules:[p],slidesPerView:1,spaceBetween:16,keyboard:{enabled:!0,onlyInViewport:!1},breakpoints:{768:{slidesPerView:2,spaceBetween:18},1440:{slidesPerView:4,spaceBetween:16}},direction:"horizontal",navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},disabledClass:"swiper-button-disabled"});const a=document.querySelector(".footer-modal"),i=document.getElementById("cooperation-comment-form"),P=document.getElementById("email"),N=document.getElementById("comment");i.addEventListener("submit",async function(e){if(e.preventDefault(),C(P.value)&&N.value.trim()!==""){const t=i.elements.email.value,n=i.elements.comment.value;await b({email:t,comment:n});try{R(),i.reset()}catch{console.log(err)}}});function C(e){return/^\w+(\.\w+)?@[a-zA-Z_]+?\.[a-zA-Z]{2,3}$/.test(e)}function R(){a.classList.remove("visually-hidden"),setTimeout(()=>a.classList.add("visually-hidden"),5e3)}const V=document.querySelector(".footer-close-btn"),m=document.querySelector(".footer-modal");V.addEventListener("click",d);m.addEventListener("click",function(e){e.target===m&&d()});document.addEventListener("keydown",function(e){e.key==="Escape"&&d()});function d(){a.classList.add("visually-hidden")}
//# sourceMappingURL=commonHelpers.js.map
